version: '2'

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    environment:
      MONGO_INITDB_DATABASE: filesharing
      MONGO_INITDB_ROOT_USERNAME: mguser
      MONGO_INITDB_ROOT_PASSWORD: mgpass
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mguser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mgpass
      ME_CONFIG_MONGODB_URL: mongodb://mguser:mgpass@mongo:27017/
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
  filesharing:
    depends_on:
      - mongo
      - redis
    ports:
      - 3000:3000
    image: filesharing
    restart: always    
    volumes:
      - filesharing_data:/usr/src/app/uploadPath
volumes:
    mongo_data:
    redis_data:
    filesharing_data:
